name: Fullstack CI/CD

on:
  pull_request:
    types: [opened]

jobs:
  build:
    name: "Build and test app"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Configure node"
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: "Install dependencies"
        run: npm install

      - name: "Run lint"
        run: npm run lint

      - name: "Run formatter"
        run: npm run prettier
    
      - name: "Run test"
        run: CI=true npm run test

      - name: "Build"
        run: npm build
    
      


      