name: Fullstack CI/CD

on:
  push:
    branches:
        - main

permissions:
    id-token: write #requesting JTW
    contents: read # actions/checkout

jobs:
  build:
    name: "Deploy app"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::758178873351:role/github_actions_role
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build and push image
        run: |
          docker build -t teste .
          docker tag teste:latest 758178873351.dkr.ecr.us-east-2.amazonaws.com/teste:latest
          docker push 758178873351.dkr.ecr.us-east-2.amazonaws.com/teste:latest